services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    ports:
      - "5800:5800"
    devices:
      - /dev/net/tun
    environment:
      - VPN_CONFIG_FILE=config.ovpn
    volumes:
      - ./config:/data/vpn
    restart: unless-stopped

  ssh-vpn-connection:
    build: .
    container_name: ssh-vpn-connection
    network_mode: service:openvpn-client
    command: tail -F anything
  
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    network_mode: service:openvpn-client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped